### ISSUE TITLE
Supress warnings for deprecated shapes

### ISSUE THREAD

**Issue by jjant** [smithy-lang/smithy-rs#2047] opened 2022-12-01 16:07 UTC
We still support a bunch of deprecated shapes (~`EnumShape`~ `EnumTrait`, `SetShape`), and these generate a lot of warnings while building.

**Comment by jdisanti** [comment] 2022-12-01 18:45
Did you mean `EnumTrait`? `EnumShape` is the new shininess.

I think we actually have a path forward to stop referencing both of these in our code. `SetShape` extends `ListShape`, so we can just stop matching on it entirely.

**Comment by 82marbag** [comment] 2022-12-02 10:01
For enums: https://github.com/awslabs/smithy-rs/pull/1932 (waiting for a conversation with the smithy team to be resolved)

I'll cut one for sets

**Comment by jjant** [comment] 2022-12-02 10:22
Yes, I meant `EnumTrait`! Good catch.

We can't remove all references of `SetShape` afaik, because things like
```kotlin
override fun setShape(shape: SetShape) {}
```
don't compile if you replace that with `ListShape`.

**Comment by jdisanti** [comment] 2024-04-05 01:01
Duplicate of #1670

**Closed by jdisanti** 2024-04-05 01:01 UTC
