### ISSUE TITLE
Implement event streaming initial messages in AwsJson

### ISSUE THREAD

**Issue by 82marbag** [smithy-lang/smithy-rs#2237] opened 2023-01-20 07:19 UTC
https://github.com/awslabs/smithy-rs/pull/2230 throws an exception if a non-streaming member and a streaming-member are in the payload of an AwsJson 1.0 request/response.

https://github.com/awslabs/smithy/issues/1584 confirmed this constraint is not required and we should relax it. Note that this is backwards compatible.

**Comment by david-perez** [comment] 2023-04-04 08:07
Relevant code:

https://github.com/awslabs/smithy-rs/blob/c901c0b1c69ddbae350529c0f8116c4ab06fd348/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/AwsJson.kt#L51-L59

In other words, this issue is saying we haven't implemented [initial messages](https://smithy.io/2.0/spec/streaming.html#initial-messages) in the awsJson1.x protocols.

**Comment by jdisanti** [comment] 2024-04-05 01:14
Duplicate of #121

**Closed by jdisanti** 2024-04-05 01:14 UTC
Labels: event-stream
